name: PlaceStory_CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        xcodebuild clean test -project PlaceStory.xcodeproj \
        -scheme PlaceStory \
        -destination "platform=iOS Simulator,name=iPhone 15,OS=latest"
